// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeSp-YLbbPnEUrEdzro-4PS2TCg4JBQxg',
    appId: '1:136044007781:web:e5ad8af1ae652ae31c518c',
    messagingSenderId: '136044007781',
    projectId: 'madhwa-hackathon',
    authDomain: 'madhwa-hackathon.firebaseapp.com',
    storageBucket: 'madhwa-hackathon.firebasestorage.app',
    measurementId: 'G-SBR5LXLPHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDVqjZdw5DIz5okGb7c-L5KFA0PA7cQgo',
    appId: '1:136044007781:android:237c8d7fd49ba0241c518c',
    messagingSenderId: '136044007781',
    projectId: 'madhwa-hackathon',
    storageBucket: 'madhwa-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdo6-1Oxj1whQcvJ2zG4JVfFajr5lCDbw',
    appId: '1:136044007781:ios:9acd9d926cc44baa1c518c',
    messagingSenderId: '136044007781',
    projectId: 'madhwa-hackathon',
    storageBucket: 'madhwa-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.karmicCanteenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdo6-1Oxj1whQcvJ2zG4JVfFajr5lCDbw',
    appId: '1:136044007781:ios:9acd9d926cc44baa1c518c',
    messagingSenderId: '136044007781',
    projectId: 'madhwa-hackathon',
    storageBucket: 'madhwa-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.karmicCanteenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeSp-YLbbPnEUrEdzro-4PS2TCg4JBQxg',
    appId: '1:136044007781:web:0e2029df0daa73c21c518c',
    messagingSenderId: '136044007781',
    projectId: 'madhwa-hackathon',
    authDomain: 'madhwa-hackathon.firebaseapp.com',
    storageBucket: 'madhwa-hackathon.firebasestorage.app',
    measurementId: 'G-ZXM41E96T4',
  );
}
